// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: net_message/net_messages.proto

package net_messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseRaftMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner    string `protobuf:"bytes,1,opt,name=Owner,json=owner,proto3" json:"Owner,omitempty"`
	Dest     string `protobuf:"bytes,2,opt,name=Dest,json=dest,proto3" json:"Dest,omitempty"`
	CurrTerm int32  `protobuf:"varint,3,opt,name=CurrTerm,json=currTerm,proto3" json:"CurrTerm,omitempty"`
}

func (x *BaseRaftMessage) Reset() {
	*x = BaseRaftMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_net_message_net_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseRaftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRaftMessage) ProtoMessage() {}

func (x *BaseRaftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_net_message_net_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRaftMessage.ProtoReflect.Descriptor instead.
func (*BaseRaftMessage) Descriptor() ([]byte, []int) {
	return file_net_message_net_messages_proto_rawDescGZIP(), []int{0}
}

func (x *BaseRaftMessage) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *BaseRaftMessage) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *BaseRaftMessage) GetCurrTerm() int32 {
	if x != nil {
		return x.CurrTerm
	}
	return 0
}

type Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Term  int32  `protobuf:"varint,1,opt,name=Term,json=term,proto3" json:"Term,omitempty"`
	Query []byte `protobuf:"bytes,2,opt,name=Query,json=query,proto3" json:"Query,omitempty"`
}

func (x *Entry) Reset() {
	*x = Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_net_message_net_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_net_message_net_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_net_message_net_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Entry) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

type AppendEntries struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg      *BaseRaftMessage `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	PrevTerm int32            `protobuf:"varint,2,opt,name=PrevTerm,json=prevTerm,proto3" json:"PrevTerm,omitempty"`
	NewIndex int32            `protobuf:"varint,3,opt,name=NewIndex,json=newIndex,proto3" json:"NewIndex,omitempty"`
	Entries  []*Entry         `protobuf:"bytes,4,rep,name=Entries,json=entries,proto3" json:"Entries,omitempty"`
}

func (x *AppendEntries) Reset() {
	*x = AppendEntries{}
	if protoimpl.UnsafeEnabled {
		mi := &file_net_message_net_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntries) ProtoMessage() {}

func (x *AppendEntries) ProtoReflect() protoreflect.Message {
	mi := &file_net_message_net_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntries.ProtoReflect.Descriptor instead.
func (*AppendEntries) Descriptor() ([]byte, []int) {
	return file_net_message_net_messages_proto_rawDescGZIP(), []int{2}
}

func (x *AppendEntries) GetMsg() *BaseRaftMessage {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AppendEntries) GetPrevTerm() int32 {
	if x != nil {
		return x.PrevTerm
	}
	return 0
}

func (x *AppendEntries) GetNewIndex() int32 {
	if x != nil {
		return x.NewIndex
	}
	return 0
}

func (x *AppendEntries) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type AppendAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg      *BaseRaftMessage `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Appended bool             `protobuf:"varint,2,opt,name=Appended,json=appended,proto3" json:"Appended,omitempty"`
}

func (x *AppendAck) Reset() {
	*x = AppendAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_net_message_net_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendAck) ProtoMessage() {}

func (x *AppendAck) ProtoReflect() protoreflect.Message {
	mi := &file_net_message_net_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendAck.ProtoReflect.Descriptor instead.
func (*AppendAck) Descriptor() ([]byte, []int) {
	return file_net_message_net_messages_proto_rawDescGZIP(), []int{3}
}

func (x *AppendAck) GetMsg() *BaseRaftMessage {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AppendAck) GetAppended() bool {
	if x != nil {
		return x.Appended
	}
	return false
}

type RequestVote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg      *BaseRaftMessage `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	TopIndex int32            `protobuf:"varint,2,opt,name=TopIndex,json=topIndex,proto3" json:"TopIndex,omitempty"`
	TopTerm  int32            `protobuf:"varint,3,opt,name=TopTerm,json=topTerm,proto3" json:"TopTerm,omitempty"`
}

func (x *RequestVote) Reset() {
	*x = RequestVote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_net_message_net_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVote) ProtoMessage() {}

func (x *RequestVote) ProtoReflect() protoreflect.Message {
	mi := &file_net_message_net_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVote.ProtoReflect.Descriptor instead.
func (*RequestVote) Descriptor() ([]byte, []int) {
	return file_net_message_net_messages_proto_rawDescGZIP(), []int{4}
}

func (x *RequestVote) GetMsg() *BaseRaftMessage {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *RequestVote) GetTopIndex() int32 {
	if x != nil {
		return x.TopIndex
	}
	return 0
}

func (x *RequestVote) GetTopTerm() int32 {
	if x != nil {
		return x.TopTerm
	}
	return 0
}

type RequestAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg   *BaseRaftMessage `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Voted bool             `protobuf:"varint,2,opt,name=Voted,json=voted,proto3" json:"Voted,omitempty"`
}

func (x *RequestAck) Reset() {
	*x = RequestAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_net_message_net_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAck) ProtoMessage() {}

func (x *RequestAck) ProtoReflect() protoreflect.Message {
	mi := &file_net_message_net_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAck.ProtoReflect.Descriptor instead.
func (*RequestAck) Descriptor() ([]byte, []int) {
	return file_net_message_net_messages_proto_rawDescGZIP(), []int{5}
}

func (x *RequestAck) GetMsg() *BaseRaftMessage {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *RequestAck) GetVoted() bool {
	if x != nil {
		return x.Voted
	}
	return false
}

var File_net_message_net_messages_proto protoreflect.FileDescriptor

var file_net_message_net_messages_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6e, 0x65, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x6e, 0x65,
	0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x57, 0x0a, 0x0f, 0x42, 0x61, 0x73, 0x65, 0x52, 0x61, 0x66, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x65, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x43, 0x75, 0x72, 0x72, 0x54, 0x65, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x63, 0x75, 0x72, 0x72, 0x54, 0x65, 0x72, 0x6d, 0x22, 0x31, 0x0a, 0x05, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x65, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x8d, 0x01, 0x0a,
	0x0d, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x22,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x61, 0x66, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x65, 0x76, 0x54, 0x65, 0x72, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x65, 0x76, 0x54, 0x65, 0x72, 0x6d, 0x12, 0x1a,
	0x0a, 0x08, 0x4e, 0x65, 0x77, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x6e, 0x65, 0x77, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x20, 0x0a, 0x07, 0x45, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x4b, 0x0a, 0x09,
	0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x41, 0x63, 0x6b, 0x12, 0x22, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x61, 0x66,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1a, 0x0a,
	0x08, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x22, 0x67, 0x0a, 0x0b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x61, 0x66, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08,
	0x54, 0x6f, 0x70, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x74, 0x6f, 0x70, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x6f, 0x70, 0x54,
	0x65, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x6f, 0x70, 0x54, 0x65,
	0x72, 0x6d, 0x22, 0x46, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x63, 0x6b,
	0x12, 0x22, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x61, 0x66, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x6f, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x6f, 0x74, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_net_message_net_messages_proto_rawDescOnce sync.Once
	file_net_message_net_messages_proto_rawDescData = file_net_message_net_messages_proto_rawDesc
)

func file_net_message_net_messages_proto_rawDescGZIP() []byte {
	file_net_message_net_messages_proto_rawDescOnce.Do(func() {
		file_net_message_net_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_net_message_net_messages_proto_rawDescData)
	})
	return file_net_message_net_messages_proto_rawDescData
}

var file_net_message_net_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_net_message_net_messages_proto_goTypes = []interface{}{
	(*BaseRaftMessage)(nil), // 0: BaseRaftMessage
	(*Entry)(nil),           // 1: Entry
	(*AppendEntries)(nil),   // 2: AppendEntries
	(*AppendAck)(nil),       // 3: AppendAck
	(*RequestVote)(nil),     // 4: RequestVote
	(*RequestAck)(nil),      // 5: RequestAck
}
var file_net_message_net_messages_proto_depIdxs = []int32{
	0, // 0: AppendEntries.msg:type_name -> BaseRaftMessage
	1, // 1: AppendEntries.Entries:type_name -> Entry
	0, // 2: AppendAck.msg:type_name -> BaseRaftMessage
	0, // 3: RequestVote.msg:type_name -> BaseRaftMessage
	0, // 4: RequestAck.msg:type_name -> BaseRaftMessage
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_net_message_net_messages_proto_init() }
func file_net_message_net_messages_proto_init() {
	if File_net_message_net_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_net_message_net_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseRaftMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_net_message_net_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_net_message_net_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendEntries); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_net_message_net_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_net_message_net_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestVote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_net_message_net_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_net_message_net_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_net_message_net_messages_proto_goTypes,
		DependencyIndexes: file_net_message_net_messages_proto_depIdxs,
		MessageInfos:      file_net_message_net_messages_proto_msgTypes,
	}.Build()
	File_net_message_net_messages_proto = out.File
	file_net_message_net_messages_proto_rawDesc = nil
	file_net_message_net_messages_proto_goTypes = nil
	file_net_message_net_messages_proto_depIdxs = nil
}
